/* ============================================================
   Agros-98 AD — Products Data
   ============================================================ */

window.AGROS_CATEGORIES = {
  seeds:   { label: 'Seeds & Kernels', color: '#598b43' },
  oils:    { label: 'Cold-Pressed Oils', color: '#d4a843' },
  flours:  { label: 'Flours & Proteins', color: '#b8723a' },
  tahinis: { label: 'Tahinis & Butters', color: '#7c5c3a' },
};

window.AGROS_PRODUCTS = [
  /* ---- SEEDS & KERNELS ---- */
  {
    slug: 'hulled-sunflower-kernels',
    name: 'Hulled Sunflower Kernels',
    category: 'seeds',
    categoryLabel: 'Seeds & Kernels',
    tagline: 'Available as Bakery, Premium Bakery, Confectionery, and Chips.',
    specs: [
      { key: 'Grades', val: '4 available' },
      { key: 'Moisture', val: 'max 7–8%' },
      { key: 'Purity', val: 'min 99.98%' },
      { key: 'Size', val: '500–700 pcs/oz' },
      { key: 'Oil Content', val: '42–52%' },
      { key: 'Origin', val: 'Bulgaria' },
    ],
    packaging: '25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags',
    moq: '1 × 40ft container',
    tags: ['Halal & Kosher', 'ISO22000', 'FSSC22000'],
    relatedSlugs: ['sunflower-oil-linoleic', 'sunflower-flour', 'sunflower-protein'],
    image: 'Media/products/sunflower-kernel.webp',
  },
  {
    slug: 'coriander',
    name: 'Coriander Seeds',
    category: 'seeds',
    categoryLabel: 'Seeds & Kernels',
    tagline: 'Available Whole or as Splits. Used for spice blends and essential oil extraction.',
    specs: [
      { key: 'Purity', val: 'min 99.5%' },
      { key: 'Moisture', val: 'max 8%' },
      { key: 'Essential Oil', val: 'min 1.1 ml/100g' },
      { key: 'Foreign Matter', val: 'max 0.3–0.5%' },
      { key: 'Origin', val: 'Bulgaria' },
    ],
    packaging: '25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags',
    moq: '1 × 40ft container',
    tags: ['Halal & Kosher', 'ISO22000', 'FSSC22000'],
    relatedSlugs: ['coriander-oil', 'coriander-flour', 'hulled-sunflower-kernels'],
    image: 'Media/products/coriander-seed.webp',
  },
  {
    slug: 'flaxseed-brown',
    name: 'Flaxseed – Brown',
    category: 'seeds',
    categoryLabel: 'Seeds & Kernels',
    tagline: 'Whole brown flaxseed, rich in omega-3 and dietary fibre, grown on own farmland.',
    specs: [
      { key: 'Moisture', val: 'max 8%' },
      { key: 'Purity', val: 'min 99.9%' },
      { key: 'Oil Content', val: '40–44%' },
      { key: 'Protein', val: '20–24%' },
      { key: 'Splits', val: 'max 3%' },
      { key: 'Color', val: 'Brown, glossy' },
    ],
    packaging: '25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags',
    moq: '1 × 40ft container',
    tags: ['Halal & Kosher', 'ISO22000', 'FSSC22000'],
    relatedSlugs: ['flaxseed-golden', 'flaxseed-oil', 'flaxseed-flour'],
    image: 'Media/products/brown-flaxseed.webp',
  },
  {
    slug: 'flaxseed-golden',
    name: 'Flaxseed – Golden',
    category: 'seeds',
    categoryLabel: 'Seeds & Kernels',
    tagline: 'Premium golden flaxseed with bright colour and mild nutty flavour.',
    specs: [
      { key: 'Moisture', val: 'max 8%' },
      { key: 'Purity', val: 'min 99.9%' },
      { key: 'Oil Content', val: '38–42%' },
      { key: 'Protein', val: '20–24%' },
      { key: 'Splits', val: 'max 3%' },
      { key: 'Color', val: 'Bright golden' },
    ],
    packaging: '25 kg paper bags / 25 kg PP bags / 50 lb paper bags / 1 000 kg Big Bags',
    moq: '1 × 40ft container',
    tags: ['Halal & Kosher', 'ISO22000', 'FSSC22000'],
    relatedSlugs: ['flaxseed-brown', 'flaxseed-oil', 'flaxseed-flour'],
    image: 'Media/products/golden-flaxseed.webp',
  },

  /* ---- COLD-PRESSED OILS ---- */
  {
    slug: 'sunflower-oil-linoleic',
    name: 'Sunflower Oil – High Linoleic',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Cold-pressed high-linoleic sunflower oil with clean flavour and high omega-6 content.',
    specs: [
      { key: 'Acid Value', val: 'max 0.5 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 5 meq/kg' },
      { key: 'Free Fatty Acids', val: 'max 0.3%' },
      { key: 'Linoleic Acid (C18:2)', val: '60–68%' },
      { key: 'Oleic Acid (C18:1)', val: '14–21%' },
      { key: 'Moisture & Volatiles', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['Cold-Pressed', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['sunflower-oil-oleic', 'sunflower-flour', 'sunflower-protein'],
    image: 'Media/products/sunflower-oil.webp',
  },
  {
    slug: 'sunflower-oil-oleic',
    name: 'Sunflower Oil – High Oleic',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Heat-stable high-oleic sunflower oil with extended shelf life and clean frying performance.',
    specs: [
      { key: 'Acid Value', val: 'max 0.5 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 5 meq/kg' },
      { key: 'Free Fatty Acids', val: 'max 0.3%' },
      { key: 'Oleic Acid (C18:1)', val: 'min 80%' },
      { key: 'Linoleic Acid (C18:2)', val: 'max 10%' },
      { key: 'Moisture & Volatiles', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['High Oleic', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['sunflower-oil-linoleic', 'sunflower-flour', 'sunflower-protein'],
    image: 'Media/products/sunflower-oil.webp',
  },
  {
    slug: 'milk-thistle-oil',
    name: 'Milk Thistle Oil',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Cold-pressed milk thistle seed oil — rich in linoleic acid, vitamin E, and bioactive silymarin compounds.',
    specs: [
      { key: 'Linoleic Acid (C18:2)', val: '50–60%' },
      { key: 'Oleic Acid (C18:1)', val: '22–28%' },
      { key: 'Palmitic Acid', val: '7–9%' },
      { key: 'Free Fatty Acids', val: 'max 1.0%' },
      { key: 'Peroxide Value', val: 'max 10 meq/kg' },
      { key: 'Moisture', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25 L drums / 200 L drums / IBC 1000 L',
    moq: '500 kg',
    tags: ['Specialty Oil', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['milk-thistle-flour', 'coriander-oil', 'flaxseed-oil'],
    image: 'Media/products/coriander-oil.webp',
  },
  {
    slug: 'coriander-oil',
    name: 'Coriander Oil',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Rare cold-pressed coriander seed oil, rich in petroselinic acid for cosmetics and food.',
    specs: [
      { key: 'Acid Value', val: 'max 2.0 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 10 meq/kg' },
      { key: 'Petroselinic Acid', val: '60–72%' },
      { key: 'Free Fatty Acids', val: 'max 1.0%' },
      { key: 'Colour (Lovibond)', val: 'Y ≤ 20, R ≤ 2.5' },
      { key: 'Moisture & Volatiles', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['Specialty Oil', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['coriander-seeds', 'coriander-flour', 'walnut-oil'],
    image: 'Media/products/coriander-oil.webp',
  },
  {
    slug: 'flaxseed-oil',
    name: 'Flaxseed Oil',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Cold-pressed linseed oil, exceptionally rich in alpha-linolenic acid (omega-3).',
    specs: [
      { key: 'Acid Value', val: 'max 1.5 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 5 meq/kg' },
      { key: 'Alpha-Linolenic Acid (C18:3)', val: '50–60%' },
      { key: 'Linoleic Acid (C18:2)', val: '12–18%' },
      { key: 'Free Fatty Acids', val: 'max 0.8%' },
      { key: 'Moisture & Volatiles', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['Omega-3 Rich', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['flaxseed-brown', 'flaxseed-golden', 'flaxseed-flour'],
    image: 'Media/products/flaxseed-oil.webp',
  },
  {
    slug: 'pumpkin-oil',
    name: 'Pumpkin Oil',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Dark, intensely flavoured cold-pressed pumpkin seed oil with high tocopherol content.',
    specs: [
      { key: 'Acid Value', val: 'max 2.0 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 10 meq/kg' },
      { key: 'Color (visual)', val: 'Dark green/amber' },
      { key: 'Tocopherols', val: 'High (natural)' },
      { key: 'Linoleic Acid (C18:2)', val: '40–55%' },
      { key: 'Oleic Acid (C18:1)', val: '25–35%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['Specialty Oil', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['pumpkin-flour', 'walnut-oil', 'coriander-oil'],
    image: 'Media/products/pumpkin-oil.webp',
  },
  {
    slug: 'walnut-oil',
    name: 'Walnut Oil',
    category: 'oils',
    categoryLabel: 'Cold-Pressed Oils',
    tagline: 'Delicate cold-pressed walnut oil with a rich, nutty profile and balanced omega-3/6 ratio.',
    specs: [
      { key: 'Acid Value', val: 'max 2.0 mg KOH/g' },
      { key: 'Peroxide Value', val: 'max 10 meq/kg' },
      { key: 'Linoleic Acid (C18:2)', val: '54–65%' },
      { key: 'Linolenic Acid (C18:3)', val: '10–14%' },
      { key: 'Oleic Acid (C18:1)', val: '14–21%' },
      { key: 'Moisture & Volatiles', val: 'max 0.1%' },
    ],
    packaging: '5 L tins / 25L drums / 200L drums / IBC 1000L',
    moq: '500 kg',
    tags: ['Specialty Oil', 'Cold-Pressed', 'Bulgarian Origin'],
    relatedSlugs: ['walnut-flour', 'pumpkin-oil', 'coriander-oil'],
    image: 'Media/products/walnut-oil.webp',
  },

  /* ---- FLOURS & PROTEINS ---- */
  {
    slug: 'sunflower-flour',
    name: 'Sunflower Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'Partially defatted sunflower flour for bakery, snacks, and high-protein formulations.',
    specs: [
      { key: 'Moisture', val: 'max 10%' },
      { key: 'Protein (db)', val: 'min 32%' },
      { key: 'Fat', val: 'max 8%' },
      { key: 'Crude Fibre', val: '14–18%' },
      { key: 'Ash', val: 'max 6%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['High Protein', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['sunflower-protein', 'sunflower-oil-linoleic', 'broken-sunflower-kernels'],
    image: 'Media/products/sunflower-flour.webp',
  },
  {
    slug: 'sunflower-protein',
    name: 'Mechanically Defatted Sunflower Protein',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'High-protein sunflower concentrate produced by mechanical cold-press defatting.',
    specs: [
      { key: 'Moisture', val: 'max 10%' },
      { key: 'Protein (db)', val: 'min 45%' },
      { key: 'Fat', val: 'max 3%' },
      { key: 'Crude Fibre', val: '12–16%' },
      { key: 'Ash', val: 'max 7%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['45%+ Protein', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['sunflower-flour', 'sunflower-oil-linoleic', 'sunflower-oil-oleic'],
    image: 'Media/products/sunflower-flour.webp',
  },
  {
    slug: 'coriander-flour',
    name: 'Coriander Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'Aromatic coriander seed flour with natural spice character for seasoning and functional use.',
    specs: [
      { key: 'Moisture', val: 'max 10%' },
      { key: 'Protein', val: '14–18%' },
      { key: 'Fat', val: '20–25%' },
      { key: 'Crude Fibre', val: '8–12%' },
      { key: 'Ash', val: 'max 6%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['Aromatic', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['coriander-seeds', 'coriander-splits', 'coriander-oil'],
    image: 'Media/products/coriander-flour.webp',
  },
  {
    slug: 'flaxseed-flour',
    name: 'Flaxseed Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'Omega-rich flaxseed flour with high fibre content for health food applications.',
    specs: [
      { key: 'Moisture', val: 'max 10%' },
      { key: 'Protein', val: '20–24%' },
      { key: 'Fat', val: '30–36%' },
      { key: 'Crude Fibre', val: '20–26%' },
      { key: 'Ash', val: 'max 5%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['Omega-3 Rich', 'High Fibre', 'Bulgarian Origin'],
    relatedSlugs: ['flaxseed-brown', 'flaxseed-golden', 'flaxseed-oil'],
    image: 'Media/products/flaxseed-flour.webp',
  },
  {
    slug: 'pumpkin-flour',
    name: 'Pumpkin Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'Mildly sweet pumpkin seed flour with distinctive green hue for specialty baking.',
    specs: [
      { key: 'Moisture', val: 'max 10%' },
      { key: 'Protein', val: '15–20%' },
      { key: 'Fat', val: '8–14%' },
      { key: 'Crude Fibre', val: '10–15%' },
      { key: 'Ash', val: 'max 5%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['Specialty', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['pumpkin-oil', 'walnut-flour', 'sunflower-flour'],
    image: 'Media/products/pumpkin-flour.webp',
  },
  {
    slug: 'walnut-flour',
    name: 'Walnut Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'Rich, buttery walnut flour with high fat content for premium patisserie and keto baking.',
    specs: [
      { key: 'Moisture', val: 'max 8%' },
      { key: 'Protein', val: '18–22%' },
      { key: 'Fat', val: '50–60%' },
      { key: 'Crude Fibre', val: '4–8%' },
      { key: 'Ash', val: 'max 2.5%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '1 × 20ft container',
    tags: ['Premium', 'Keto-Friendly', 'Bulgarian Origin'],
    relatedSlugs: ['walnut-oil', 'pumpkin-flour', 'sunflower-flour'],
    image: 'Media/products/walnut-flour.webp',
  },

  {
    slug: 'milk-thistle-flour',
    name: 'Milk Thistle Flour',
    category: 'flours',
    categoryLabel: 'Flours & Proteins',
    tagline: 'High-silymarin milk thistle seed flour — a functional ingredient for nutraceutical and specialty food applications.',
    specs: [
      { key: 'Moisture', val: 'max 6%' },
      { key: 'Protein', val: '20–24%' },
      { key: 'Fat', val: '5–6%' },
      { key: 'Crude Fibre', val: '5–7%' },
      { key: 'Ash', val: 'max 2.5%' },
      { key: 'Particle Size', val: '≤ 500 µm' },
    ],
    packaging: '25 kg paper bags / Big bags 500–1000 kg',
    moq: '500 kg',
    tags: ['High Silymarin', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['milk-thistle-oil', 'sunflower-flour', 'flaxseed-flour'],
    image: 'Media/products/sunflower-flour.webp',
  },

  /* ---- TAHINIS & BUTTERS ---- */
  {
    slug: 'sunflower-tahini',
    name: 'Sunflower Creamy Tahini',
    category: 'tahinis',
    categoryLabel: 'Tahinis & Butters',
    tagline: 'Smooth, stone-ground sunflower seed butter with a mild, nutty flavour and high spreadability.',
    specs: [
      { key: 'Moisture', val: 'max 1%' },
      { key: 'Oil Content', val: '48–54%' },
      { key: 'Protein', val: 'min 20%' },
      { key: 'Ash', val: 'max 4%' },
      { key: 'Free Fatty Acids', val: 'max 1%' },
      { key: 'Texture', val: 'Smooth / creamy' },
    ],
    packaging: '300g jars / 1 kg tubs / 5 kg pails / 25 kg drums',
    moq: '500 kg',
    tags: ['Non-GMO', 'Bulgarian Origin', 'No Additives'],
    relatedSlugs: ['hulled-sunflower-kernels', 'sunflower-flour', 'pumpkin-tahini'],
    image: 'Media/products/tahini.webp',
  },
  {
    slug: 'flaxseed-tahini',
    name: 'Flaxseed Creamy Tahini',
    category: 'tahinis',
    categoryLabel: 'Tahinis & Butters',
    tagline: 'Omega-3-rich flaxseed butter with an earthy flavour and exceptional nutritional profile.',
    specs: [
      { key: 'Moisture', val: 'max 1%' },
      { key: 'Oil Content', val: '38–44%' },
      { key: 'Protein', val: 'min 18%' },
      { key: 'Omega-3 (ALA)', val: '50–60% of fatty acids' },
      { key: 'Free Fatty Acids', val: 'max 1%' },
      { key: 'Texture', val: 'Smooth / creamy' },
    ],
    packaging: '300g jars / 1 kg tubs / 5 kg pails / 25 kg drums',
    moq: '500 kg',
    tags: ['Omega-3 Rich', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['flaxseed-brown', 'flaxseed-oil', 'sunflower-tahini'],
    image: 'Media/products/flaxseed-tahini.webp',
  },
  {
    slug: 'pumpkin-tahini',
    name: 'Pumpkin Creamy Tahini',
    category: 'tahinis',
    categoryLabel: 'Tahinis & Butters',
    tagline: 'Rich, distinctively green pumpkin seed butter packed with zinc and tocopherols.',
    specs: [
      { key: 'Moisture', val: 'max 1%' },
      { key: 'Oil Content', val: '42–50%' },
      { key: 'Protein', val: 'min 22%' },
      { key: 'Zinc', val: 'High (natural)' },
      { key: 'Free Fatty Acids', val: 'max 1%' },
      { key: 'Texture', val: 'Smooth / creamy' },
    ],
    packaging: '300g jars / 1 kg tubs / 5 kg pails / 25 kg drums',
    moq: '500 kg',
    tags: ['Zinc-Rich', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['pumpkin-seed', 'pumpkin-oil', 'sunflower-tahini'],
    image: 'Media/products/pumpkin-tahini.webp',
  },
  {
    slug: 'walnut-tahini',
    name: 'Walnut Creamy Tahini',
    category: 'tahinis',
    categoryLabel: 'Tahinis & Butters',
    tagline: 'Premium stone-ground walnut butter with rich, buttery flavour and balanced omega-3/6 profile.',
    specs: [
      { key: 'Moisture', val: 'max 1%' },
      { key: 'Oil Content', val: '55–65%' },
      { key: 'Protein', val: 'min 14%' },
      { key: 'Omega-3 (ALA)', val: '10–14% of fatty acids' },
      { key: 'Free Fatty Acids', val: 'max 1%' },
      { key: 'Texture', val: 'Smooth / creamy' },
    ],
    packaging: '300g jars / 1 kg tubs / 5 kg pails / 25 kg drums',
    moq: '500 kg',
    tags: ['Premium', 'Non-GMO', 'Bulgarian Origin'],
    relatedSlugs: ['walnut-oil', 'walnut-flour', 'sunflower-tahini'],
    image: 'Media/products/tahini.webp',
  },
];
